### ISSUE TITLE
Does not work in FreeVSD/PC-BSD :[

### ISSUE THREAD

**Issue by liar666** [b4n/clawsmail-password-decrypter#3]
As stated at the end of the README.md the python script does not work in FreeBSD/PC-BSD :{

I get an answer, but it's wrong :)
password for xm@xxx@imap.gmail.com, xm@xxx is "P��(�,����Q..."

Maybe you can get help from BSD guys, like:
http://www.bsdnow.tv/
https://www.pcbsd.org/
They are very cool. Or directly from ClawsMail devs?

By the way, what's/where's the key we are supposed to provide to your tool?

**Comment by b4n** [comment]
I just tried to re-read the C version and understand what was going on, and concluded to the same as last time: the encryption just couldn't work.  But I then went ahead and actually tried to see what would happen if I did the same as ClawsMail here, and that's probably it: encryption fails, but silently, so actually nothing happens.  See https://github.com/b4n/clawsmail-password-decrypter#note-on-encryption-under-freebsd-des-ecb

So in the end if the password has a length not multiple of 8 bytes, it's only "encoded" with base64, nothing more.  If the length is multiple of 8, it uses normal ECB.

I updated the tool to do that when the mode is ECB (new `--mode` option), and it should work now.  Could you please try it out?  `--mode=ECB` or `--freebsd`.

**Comment by liar666** [comment]
I just downloaded the new zip and tried, it did not work :[

**Comment by b4n** [comment]
Bummer… could you provide me some actual samples from a FreeBSD ClawsMail then?  Not your real passwords of course, but some actual values I could uses as a test basis?

**Comment by b4n** [comment]
BTW, newest ClawsMail development version seems to have introduced a more solid password encryption scheme with a real master password, so next versions won't be as easy to break (which is nice when you don't have to recover them).  If you happen to use that (unlikely I guess) there won't be much we can do I'm afraid.

**Comment by liar666** [comment]
Yeah would be great if there's a better protection of the passwords... I'm not sure what is the latest version, but I use version 3.13.1.

You'll find a small .claws-mail configuration dir here:
https://mega.nz/#!RAtQEIYa!ZTXvp4dcimwMkBZRH5SGvB03CELWMIb0S-qSw_Y9fh8

account is: Jm@absens.com  (not sure about the uppercase 1rst letter...)
password is: plop

**Comment by b4n** [comment]
Fixed in 754f8e3560a2825ba604e489ab115e46deda2440.  It was a stupid bug on my part: I forgot to forward the selected chaining mode when parsing an accountrc.  It now works just fine with your example, thanks!

**Comment by liar666** [comment]
Unfortunately, it still does not work with my true account :[
Maybe there's a difference because I use a complex password for my true account?
I'll try to create a .claws-mail/ that is more similar to the one of my actual account...

**Comment by b4n** [comment]
> Unfortunately, it still does not work with my true account :[

Damn :(

> Maybe there's a difference because I use a complex password for my true account?

Would be odd, but not impossible.  If your password has a multiple of 8 bytes (8, 16, 24, 32, …), it would be encoded for "real" and not simply base64ed, so if for some reason my Python code path doesn't work as it should it might fail.  But I tried several input I forged (ok, not actually on FreeBSD, but the glibc code seem pretty much the same), really encrypted and not, and all worked fine, so I somewhat doubt it.

> I'll try to create a .claws-mail/ that is more similar to the one of my actual account...

Yeah if you could send your real problematic one it would be great for figuring this out, but it's probably not an option.  Just to be sure, what kind of answer do you get, gibberish or something readable but incorrect?  It's highly unlikely it can be decrypted to something readable yet not the real value stored, so if it's not gibberish I'd be afraid the decryption is correct but for some other reason the password doesn't work…

**Comment by liar666** [comment]
Hi again,

Thanks for your patience. I've changed my password, so I could eventually send you my old .accountrc, but if I do, I would prefer to send it only to you, not to the whole world :).
Do you know if there is a way to do that in github? I can't find any "private message" section :[

Also, if it works for you with "plop", whereas it didn't work for me, I think the problem is elsewhere :[ Maybe the version of claws-mail/python/glibc I use? Would you like more info on this?

**Comment by b4n** [comment]
> Thanks for your patience. I've changed my password, so I could eventually send you my old .accountrc, but if I do, I would prefer to send it only to you, not to the whole world :).
Do you know if there is a way to do that in github? I can't find any "private message" section :[

I don't think GitHub provides that, but you can use my email address as shown in the commit messages.

> Also, if it works for you with "plop", whereas it didn't work for me, I think the problem is elsewhere :[ 

It did work for me, successfully decrypted password "plop":
```console
$ ./clawsmail-passdecrypt.py --freebsd /tmp/accountrc
password for gmuller@pop.localhost, Jm@absens.com is "plop"
```

Not working for you is awfully odd, especially as here the password is not really encrypted but only base64ed, and you could "decrypt" it by hand quite easily:
```console
$ sed -n '/^password=/{s/^[^=]*=!//p;q}' /tmp/accountrc | openssl enc -d -base64; echo
plop
```

> Maybe the version of claws-mail/python/glibc I use? Would you like more info on this? 

Mmyeah, anythig might help.  OS specifics, Python version, Python-crypto version, etc.  If needed maybe I could even setup a virtual machine as close as your system as possible.

**Comment by liar666** [comment]
You're right it's strange because when I run your sed line or :
 cat .claws-mail/accountrc | grep "^password=" | cut -d '=' -f 2 | gbase64 -d -i
I actually get my passord decoded....
It's probably that I didn't get correctly the last version from github...  :{

**Comment by liar666** [comment]
OK I git-cloned the code again, re-ran it and it works!!!!
Thanks!!!
Now I just have to wait that the claws-mail team protects the password better!!!

Thanks a lot!!!
PS: I've suggested the LaZagne devs ( https://github.com/AlessandroZ/LaZagne ) to include your tools :)
